version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/strands-py"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci(python)"
    groups:
      dev-dependencies:
        patterns:
          - "pytest"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 100
    commit-message:
      prefix: "ci(typescript)"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      development-dependencies:
        dependency-type: 'development'
        applies-to: version-updates
      production-minor:
        dependency-type: 'production'
        applies-to: version-updates
        update-types:
          - 'minor'
          - 'patch'
  - package-ecosystem: 'pip'
    directory: '/strands-py-wasm'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: "ci(python)"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: ci
