"""Strands Agents SDK Python surface.

Wire types live in :mod:`strands._generated`, auto-generated by ``bindgen``.
Those classes are accepted directly by wasmtime-py at the FFI boundary:
kebab-case record attributes, ``Variant(tag, payload)`` for tagged variants,
raw payloads for untagged ones.

This module wraps the wire types with ergonomic Python helpers: builders
that take snake_case kwargs, factories that fill variant arms, and SDK-level
event classes that lift wire-shape ``StreamEvent`` values into a typed Python
class hierarchy so users can dispatch with ``isinstance``.
"""

from __future__ import annotations

import asyncio
import inspect
import json
import typing
from collections.abc import AsyncIterator, Awaitable, Callable, Iterable
from dataclasses import asdict, is_dataclass
from typing import Any, Protocol, TypeVar, get_type_hints, runtime_checkable

from strands import _generated as _t
from strands._generated import *  # noqa: F401,F403  re-export every generated type


class StrandsError(Exception):
    """Base class for all SDK-raised errors."""


class _ModelErrorBase(StrandsError):
    """Base for errors surfaced by a model provider."""


class ContextWindowOverflowError(_ModelErrorBase):
    """Input exceeded the model's context window and no recovery was possible."""


class MaxTokensError(_ModelErrorBase):
    """Model stopped generating because it hit the max-tokens budget."""

    def __init__(self, message: str, partial_message: _t.Message | None = None) -> None:
        super().__init__(message)
        self.partial_message = partial_message


class ModelThrottledError(_ModelErrorBase):
    """Model provider throttled the request. Hook into retry to recover."""


class ProviderTokenCountError(_ModelErrorBase):
    """Provider-native token counting failed; base heuristic should run instead."""


class ToolValidationError(StrandsError):
    """A tool failed validation at registration or invocation time."""


class JsonValidationError(StrandsError):
    """A value could not be serialized to JSON."""


class StructuredOutputError(StrandsError):
    """Model refused to use the structured-output tool even after being forced."""


class ConcurrentInvocationError(StrandsError):
    """Agent is already processing an invocation; concurrent calls are not allowed."""


class SessionError(StrandsError):
    """Session storage read/write failed."""


# Inputs Message / PromptInput accept. Plain strings auto-wrap as text.
_ContentInput = (
    str
    | _t.TextBlock
    | _t.JsonBlock
    | _t.ToolUseBlock
    | _t.ToolResultBlock
    | _t.ReasoningBlock
    | _t.CachePointBlock
    | _t.ImageBlock
    | _t.VideoBlock
    | _t.DocumentBlock
    | _t.CitationsBlock
    | _t.InterruptResponseBlock
    | Any  # already-built ContentBlock variants are passed through
)


def _as_content_block(item: Any) -> Any:
    """Wrap any accepted content shape as a ``ContentBlock`` variant arm."""
    if isinstance(item, str):
        return _t.ContentBlock_Text(_t.TextBlock(text=item))
    if isinstance(item, _t.TextBlock):
        return _t.ContentBlock_Text(item)
    if isinstance(item, _t.JsonBlock):
        return _t.ContentBlock_Json(item)
    if isinstance(item, _t.ToolUseBlock):
        return _t.ContentBlock_ToolUse(item)
    if isinstance(item, _t.ToolResultBlock):
        return _t.ContentBlock_ToolResult(item)
    if isinstance(item, _t.ReasoningBlock):
        return _t.ContentBlock_Reasoning(item)
    if isinstance(item, _t.CachePointBlock):
        return _t.ContentBlock_CachePoint(item)
    if isinstance(item, _t.ImageBlock):
        return _t.ContentBlock_Image(item)
    if isinstance(item, _t.VideoBlock):
        return _t.ContentBlock_Video(item)
    if isinstance(item, _t.DocumentBlock):
        return _t.ContentBlock_Document(item)
    if isinstance(item, _t.CitationsBlock):
        return _t.ContentBlock_Citations(item)
    if isinstance(item, _t.InterruptResponseBlock):
        return _t.ContentBlock_InterruptResponse(item)
    return item  # already a ContentBlock variant


class ImageBlock(_t.ImageBlock):
    def __init__(
        self,
        *,
        format: str,
        bytes: bytes | None = None,
        url: str | None = None,
        s3: _t.S3Location | None = None,
    ) -> None:
        provided = [x for x in (bytes, url, s3) if x is not None]
        if len(provided) != 1:
            raise ValueError("ImageBlock requires exactly one of bytes, url, or s3")
        if bytes is not None:
            source = _t.ImageSource_Bytes(bytes)
        elif url is not None:
            source = _t.ImageSource_Url(url)
        else:
            assert s3 is not None
            source = _t.ImageSource_S3(s3)
        super().__init__(format=format, source=source)


class VideoBlock(_t.VideoBlock):
    def __init__(
        self,
        *,
        format: str,
        bytes: bytes | None = None,
        s3: _t.S3Location | None = None,
    ) -> None:
        if (bytes is None) == (s3 is None):
            raise ValueError("VideoBlock requires exactly one of bytes or s3")
        source = _t.VideoSource_Bytes(bytes) if bytes is not None else _t.VideoSource_S3(s3)
        super().__init__(format=format, source=source)


class DocumentBlock(_t.DocumentBlock):
    def __init__(
        self,
        *,
        name: str,
        format: str,
        bytes: bytes | None = None,
        text: str | None = None,
        content: list[_t.TextBlock] | None = None,
        s3: _t.S3Location | None = None,
        citations: bool = False,
        context: str | None = None,
    ) -> None:
        provided = [x for x in (bytes, text, content, s3) if x is not None]
        if len(provided) != 1:
            raise ValueError("DocumentBlock requires exactly one of bytes, text, content, or s3")
        if bytes is not None:
            source = _t.DocumentSource_Bytes(bytes)
        elif text is not None:
            source = _t.DocumentSource_Text(text)
        elif content is not None:
            source = _t.DocumentSource_Content(content)
        else:
            assert s3 is not None
            source = _t.DocumentSource_S3(s3)
        super().__init__(
            name=name,
            format=format,
            source=source,
            citations=_t.DocumentCitationsConfig(enabled=citations) if citations else None,
            context=context,
        )


class InterruptResponseBlock(_t.InterruptResponseBlock):
    def __init__(self, *, interrupt_id: str, response: Any) -> None:
        payload = response if isinstance(response, str) else json.dumps(response)
        super().__init__(interrupt_id=interrupt_id, response=payload)


class Message(_t.Message):
    def __init__(
        self,
        *,
        role: _t.Role,
        content: Iterable[Any],
        metadata: _t.MessageMetadata | None = None,
    ) -> None:
        super().__init__(
            role=role,
            content=[_as_content_block(c) for c in content],
            metadata=metadata,
        )

    @classmethod
    def user(cls, *content: Any, metadata: _t.MessageMetadata | None = None) -> Message:
        return cls(role=_t.Role.USER, content=content, metadata=metadata)

    @classmethod
    def assistant(cls, *content: Any, metadata: _t.MessageMetadata | None = None) -> Message:
        return cls(role=_t.Role.ASSISTANT, content=content, metadata=metadata)


def _extras_to_json(extras: dict[str, Any] | None) -> str | None:
    return json.dumps(extras) if extras else None


def BedrockModel(
    model_id: str = "us.anthropic.claude-opus-4-7-v1:0",
    *,
    region: str | None = None,
    access_key_id: str | None = None,
    secret_access_key: str | None = None,
    session_token: str | None = None,
    **extras: Any,
) -> Any:
    """Build a Bedrock ``model-config`` value."""
    # The wasm bundle links the AWS SDK browser build, which has no credential
    # chain. Resolve via botocore so users get the same behavior they'd get
    # from any other Python AWS app (env vars, ~/.aws, SSO, IMDS, etc.).
    if access_key_id is None and secret_access_key is None:
        try:
            import botocore.session

            creds = botocore.session.Session().get_credentials()
            if creds is not None:
                frozen = creds.get_frozen_credentials()
                access_key_id = frozen.access_key
                secret_access_key = frozen.secret_key
                session_token = frozen.token
        except ImportError:
            pass

    return _t.ModelConfig_Bedrock(
        _t.BedrockConfig(
            model_id=model_id,
            region=region,
            access_key_id=access_key_id,
            secret_access_key=secret_access_key,
            session_token=session_token,
            additional_config=_extras_to_json(extras),
        )
    )


def AnthropicModel(model_id: str | None = None, *, api_key: str | None = None, **extras: Any) -> Any:
    return _t.ModelConfig_Anthropic(
        _t.AnthropicConfig(model_id=model_id, api_key=api_key, additional_config=_extras_to_json(extras))
    )


def OpenAIModel(model_id: str | None = None, *, api_key: str | None = None, **extras: Any) -> Any:
    return _t.ModelConfig_Openai(
        _t.OpenaiConfig(model_id=model_id, api_key=api_key, additional_config=_extras_to_json(extras))
    )


def GoogleModel(model_id: str | None = None, *, api_key: str | None = None, **extras: Any) -> Any:
    return _t.ModelConfig_Gemini(
        _t.GeminiConfig(model_id=model_id, api_key=api_key, additional_config=_extras_to_json(extras))
    )


def CustomModel(
    provider_id: str,
    *,
    model_id: str | None = None,
    stateful: bool = False,
    **extras: Any,
) -> Any:
    """Host-implemented provider. Pair with a ``model-provider`` callback."""
    return _t.ModelConfig_Custom(
        _t.CustomModelConfig(
            provider_id=provider_id,
            model_id=model_id,
            additional_config=_extras_to_json(extras),
            stateful=stateful,
        )
    )


class PydanticTool:
    """Tool whose input schema is derived from a pydantic ``BaseModel``."""

    def __init__(
        self,
        *,
        name: str,
        description: str,
        input_model: type,
        func: Callable[..., Any],
    ) -> None:
        if not hasattr(input_model, "model_json_schema") or not hasattr(input_model, "model_validate"):
            raise TypeError(f"input_model must be a pydantic BaseModel subclass; got {input_model!r}")
        self.name = name
        self.description = description
        self._input_model = input_model
        self.input_schema = input_model.model_json_schema()
        self.func = func

    def to_spec(self) -> _t.ToolSpec:
        return _t.ToolSpec(
            name=self.name,
            description=self.description,
            input_schema=json.dumps(self.input_schema),
        )

    def invoke(self, raw_input: str) -> list[Any]:
        payload = json.loads(raw_input) if raw_input else {}
        validated = self._input_model.model_validate(payload)
        return _coerce_tool_result(self.func(validated))


class Tool:
    """Registered tool: spec plus Python callable."""

    def __init__(
        self,
        *,
        name: str,
        description: str,
        input_schema: dict[str, Any],
        func: Callable[..., Any],
    ) -> None:
        self.name = name
        self.description = description
        self.input_schema = input_schema
        self.func = func

    def to_spec(self) -> _t.ToolSpec:
        return _t.ToolSpec(
            name=self.name,
            description=self.description,
            input_schema=json.dumps(self.input_schema),
        )

    def invoke(self, raw_input: str) -> list[Any]:
        kwargs = json.loads(raw_input) if raw_input else {}
        return _coerce_tool_result(self.func(**kwargs))


def _coerce_tool_result(result: Any) -> list[Any]:
    if isinstance(result, str):
        return [_t.ToolResultContent_Text(_t.TextBlock(text=result))]
    if isinstance(result, _t.TextBlock):
        return [_t.ToolResultContent_Text(result)]
    if isinstance(result, _t.JsonBlock):
        return [_t.ToolResultContent_Json(result)]
    if isinstance(result, dict):
        return [_t.ToolResultContent_Json(_t.JsonBlock(json=json.dumps(result)))]
    if is_dataclass(result) and not isinstance(result, type):
        return [_t.ToolResultContent_Json(_t.JsonBlock(json=json.dumps(asdict(result))))]
    if isinstance(result, list):
        return result
    return [_t.ToolResultContent_Text(_t.TextBlock(text=str(result)))]


def _py_type_to_schema(py_type: Any) -> dict[str, Any]:
    import types

    origin = typing.get_origin(py_type)

    # Strip Annotated[T, ...] -- only the runtime type matters for the schema.
    if origin is typing.Annotated:
        return _py_type_to_schema(typing.get_args(py_type)[0])

    # Optional[T] / Union[T, None] / T | None: emit T's schema and mark nullable.
    if origin is typing.Union or origin is types.UnionType:
        args = typing.get_args(py_type)
        non_none = [a for a in args if a is not type(None)]
        nullable = len(non_none) != len(args)
        if len(non_none) == 1:
            schema = _py_type_to_schema(non_none[0])
            if nullable:
                schema = {**schema, "nullable": True}
            return schema
        return {}  # heterogeneous union -- caller should supply input_schema

    if py_type is str:
        return {"type": "string"}
    if py_type is int:
        return {"type": "integer"}
    if py_type is float:
        return {"type": "number"}
    if py_type is bool:
        return {"type": "boolean"}
    if origin is list:
        args = typing.get_args(py_type)
        return {"type": "array", "items": _py_type_to_schema(args[0]) if args else {}}
    if origin is dict:
        return {"type": "object"}
    if origin is typing.Literal:
        return {"enum": list(typing.get_args(py_type))}
    return {}


def tool(
    func: Callable[..., Any] | None = None,
    *,
    name: str | None = None,
    description: str | None = None,
) -> Any:
    """Decorator that turns a Python function into a :class:`Tool`."""

    def wrap(f: Callable[..., Any]) -> Tool:
        hints = get_type_hints(f)
        sig = inspect.signature(f)
        properties: dict[str, Any] = {}
        required: list[str] = []
        for param_name, param in sig.parameters.items():
            properties[param_name] = _py_type_to_schema(hints.get(param_name, str))
            if param.default is inspect.Parameter.empty:
                required.append(param_name)
        schema: dict[str, Any] = {"type": "object", "properties": properties}
        if required:
            schema["required"] = required
        return Tool(
            name=name or f.__name__,
            description=description or (f.__doc__ or "").strip() or f.__name__,
            input_schema=schema,
            func=f,
        )

    return wrap(func) if func is not None else wrap


def NullConversationManager() -> Any:
    """No management. History grows without bound."""
    return _t.ConversationManagerConfig_None()


def SlidingWindowConversationManager(
    *, window_size: int = 40, should_truncate_results: bool = True
) -> Any:
    return _t.ConversationManagerConfig_SlidingWindow(
        _t.SlidingWindowConfig(window_size=window_size, should_truncate_results=should_truncate_results)
    )


def SummarizingConversationManager(
    *,
    summary_ratio: float = 0.3,
    preserve_recent_messages: int = 10,
    summarization_system_prompt: str | None = None,
    summarization_model: Any = None,
) -> Any:
    return _t.ConversationManagerConfig_Summarizing(
        _t.SummarizingConfig(
            summary_ratio=summary_ratio,
            preserve_recent_messages=preserve_recent_messages,
            summarization_system_prompt=summarization_system_prompt,
            summarization_model=summarization_model,
        )
    )


def _seconds_to_ns(seconds: float) -> int:
    return int(seconds * 1_000_000_000)


def _optional_ns(seconds: float | None) -> int | None:
    return None if seconds is None else _seconds_to_ns(seconds)


def ConstantBackoff(*, delay: float = 1.0) -> Any:
    return _t.BackoffStrategy_Constant(_t.ConstantBackoffConfig(delay=_seconds_to_ns(delay)))


def LinearBackoff(
    *,
    base: float = 1.0,
    max: float = 30.0,
    jitter: _t.JitterKind = _t.JitterKind.FULL,
) -> Any:
    return _t.BackoffStrategy_Linear(
        _t.LinearBackoffConfig(base=_seconds_to_ns(base), max=_seconds_to_ns(max), jitter=jitter)
    )


def ExponentialBackoff(
    *,
    base: float = 1.0,
    max: float = 30.0,
    factor: float = 2.0,
    jitter: _t.JitterKind = _t.JitterKind.FULL,
) -> Any:
    return _t.BackoffStrategy_Exponential(
        _t.ExponentialBackoffConfig(
            base=_seconds_to_ns(base),
            max=_seconds_to_ns(max),
            factor=factor,
            jitter=jitter,
        )
    )


class ModelRetryStrategy(_t.ModelRetryStrategy):
    def __init__(
        self,
        *,
        max_attempts: int = 6,
        backoff: Any = None,
        total_budget: float | None = None,
    ) -> None:
        super().__init__(
            max_attempts=max_attempts,
            backoff=backoff if backoff is not None else ExponentialBackoff(),
            total_budget=_optional_ns(total_budget),
        )


def FileStorage(base_dir: str) -> Any:
    return _t.StorageConfig_File(_t.FileStorageConfig(base_dir=base_dir))


def S3Storage(*, bucket: str, region: str | None = None, prefix: str | None = None) -> Any:
    return _t.StorageConfig_S3(_t.S3StorageConfig(bucket=bucket, region=region, prefix=prefix))


def CustomStorage(backend_id: str) -> Any:
    """Host-implemented backend. Pair with a ``snapshot-storage`` handler."""
    return _t.StorageConfig_Custom(_t.CustomStorageConfig(backend_id=backend_id))


class SessionManager(_t.SessionConfig):
    """Attach session persistence to an agent."""

    def __init__(
        self,
        *,
        session_id: str,
        storage: Any,
        save_latest: Any = None,
    ) -> None:
        super().__init__(session_id=session_id, storage=storage, save_latest=save_latest)


def _coerce_nested_config(value: Any) -> str:
    if isinstance(value, str):
        return value
    return json.dumps(value, default=_json_default)


def _json_default(obj: Any) -> Any:
    if is_dataclass(obj) and not isinstance(obj, type):
        return asdict(obj)
    if hasattr(obj, "__dict__"):
        return {k: v for k, v in obj.__dict__.items() if not k.startswith("_")}
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


def AgentNode(
    *,
    id: str,
    agent_config: Any,
    description: str | None = None,
    timeout: float | None = None,
) -> Any:
    return _t.NodeConfig_Agent(
        _t.AgentNodeConfig(
            id=id,
            description=description,
            timeout=_optional_ns(timeout),
            agent_config=_coerce_nested_config(agent_config),
        )
    )


def MultiAgentNode(*, id: str, orchestrator: Any, description: str | None = None) -> Any:
    return _t.NodeConfig_MultiAgent(
        _t.MultiAgentNodeConfig(
            id=id,
            description=description,
            orchestrator=_coerce_nested_config(orchestrator),
        )
    )


class Graph(_t.GraphConfig):
    def __init__(
        self,
        *,
        id: str,
        nodes: list[Any],
        edges: list[Any] | None = None,
        sources: list[str] | None = None,
        max_concurrency: int | None = None,
        max_steps: int | None = None,
        timeout: float | None = None,
        node_timeout: float | None = None,
    ) -> None:
        super().__init__(
            id=id,
            nodes=nodes,
            edges=edges or [],
            sources=sources or [],
            max_concurrency=max_concurrency,
            max_steps=max_steps,
            timeout=_optional_ns(timeout),
            node_timeout=_optional_ns(node_timeout),
        )


class Swarm(_t.SwarmConfig):
    def __init__(
        self,
        *,
        id: str,
        nodes: list[Any],
        start_node_id: str,
        max_steps: int | None = None,
        timeout: float | None = None,
        node_timeout: float | None = None,
    ) -> None:
        super().__init__(
            id=id,
            nodes=nodes,
            start_node_id=start_node_id,
            max_steps=max_steps,
            timeout=_optional_ns(timeout),
            node_timeout=_optional_ns(node_timeout),
        )


def BashTool(*, default_timeout: int | None = None) -> Any:
    return _t.VendedTool_Bash(_t.BashToolConfig(default_timeout_s=default_timeout))


def FileEditorTool(*, workspace_root: str | None = None) -> Any:
    return _t.VendedTool_FileEditor(_t.FileEditorToolConfig(workspace_root=workspace_root))


def HttpRequestTool(*, allowed_hosts: list[str] | None = None, max_response_bytes: int = 0) -> Any:
    return _t.VendedTool_HttpRequest(
        _t.HttpRequestToolConfig(
            allowed_hosts=allowed_hosts or [],
            max_response_bytes=max_response_bytes,
        )
    )


def NotebookTool(*, workspace_root: str | None = None) -> Any:
    return _t.VendedTool_Notebook(_t.NotebookToolConfig(workspace_root=workspace_root))


def SkillsPlugin(
    *,
    skills: list[str],
    strict: bool = False,
    max_resource_files: int | None = None,
    state_key: str | None = None,
) -> Any:
    return _t.VendedPlugin_Skills(
        _t.SkillsPluginConfig(
            skills=[_t.SkillSource(path=p) for p in skills],
            strict=strict,
            max_resource_files=max_resource_files,
            state_key=state_key,
        )
    )


def ContextOffloaderPlugin(
    *,
    max_result_tokens: int | None = None,
    preview_tokens: int | None = None,
    include_retrieval_tool: bool = True,
) -> Any:
    return _t.VendedPlugin_ContextOffloader(
        _t.ContextOffloaderPluginConfig(
            max_result_tokens=max_result_tokens,
            preview_tokens=preview_tokens,
            include_retrieval_tool=include_retrieval_tool,
        )
    )


def StdioMcpTransport(
    *,
    command: str,
    args: list[str] | None = None,
    env: dict[str, str] | None = None,
    cwd: str | None = None,
) -> Any:
    """Launch an MCP server as a subprocess and talk to it over stdio."""
    return _t.McpTransport_Stdio(
        _t.StdioTransportConfig(
            command=command,
            args=args or [],
            env=[_t.EnvVar(key=k, value=v) for k, v in (env or {}).items()],
            cwd=cwd,
        )
    )


def StreamableHttpMcpTransport(*, url: str, headers: dict[str, str] | None = None) -> Any:
    """Talk to a hosted MCP server over streamable HTTP."""
    return _t.McpTransport_StreamableHttp(
        _t.HttpTransportConfig(
            url=url,
            headers=[_t.HttpHeader(name=k, value=v) for k, v in (headers or {}).items()],
        )
    )


def SseMcpTransport(*, url: str, headers: dict[str, str] | None = None) -> Any:
    """Legacy SSE transport."""
    return _t.McpTransport_Sse(
        _t.SseTransportConfig(
            url=url,
            headers=[_t.HttpHeader(name=k, value=v) for k, v in (headers or {}).items()],
        )
    )


class McpClient(_t.McpClientConfig):
    """Declare an MCP client the host should open and route tools from."""

    def __init__(
        self,
        *,
        client_id: str,
        transport: Any,
        application_name: str | None = None,
        application_version: str | None = None,
        tasks_ttl: float | None = None,
        tasks_poll_timeout: float | None = None,
        elicitation_enabled: bool = False,
        fail_open: bool = False,
        disable_instrumentation: bool = False,
    ) -> None:
        tasks = None
        if tasks_ttl is not None or tasks_poll_timeout is not None:
            tasks = _t.TasksConfig(
                ttl=_seconds_to_ns(tasks_ttl if tasks_ttl is not None else 60.0),
                poll_timeout=_seconds_to_ns(tasks_poll_timeout if tasks_poll_timeout is not None else 300.0),
            )
        super().__init__(
            client_id=client_id,
            application_name=application_name,
            application_version=application_version,
            transport=transport,
            tasks_config=tasks,
            elicitation_enabled=elicitation_enabled,
            fail_open=fail_open,
            disable_instrumentation=disable_instrumentation,
        )


class InterruptResponse(_t.RespondArgs):
    """Reply to a paused agent via ``response-stream.respond``."""

    def __init__(self, *, interrupt_id: str, response: Any) -> None:
        payload = response if isinstance(response, str) else json.dumps(response)
        super().__init__(interrupt_id=interrupt_id, response=payload)



_ToolInput = Tool | PydanticTool | Callable[..., Any]
_ToolChoiceInput = Any  # tagged ToolChoice variant or "name" shorthand or None


def _coerce_tool(item: _ToolInput) -> Tool | PydanticTool:
    if isinstance(item, (Tool, PydanticTool)):
        return item
    if callable(item):
        return tool(item)
    raise TypeError(f"unsupported tool: {type(item).__name__}")


def _coerce_prompt(value: Any) -> Any:
    """Coerce a string, content blocks, or pre-built value to a ``prompt-input``."""
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        return [_as_content_block(c) for c in value]
    if hasattr(value, "__iter__") and not isinstance(value, (bytes, str)):
        return [_as_content_block(c) for c in value]
    return value


def _coerce_tool_choice(value: _ToolChoiceInput) -> Any:
    if value is None:
        return None
    if isinstance(value, str):
        return _t.ToolChoice_Named(value)
    return value


class Agent:
    """Strands agent. Construct once; call :meth:`invoke` or :meth:`stream_async`."""

    def __init__(
        self,
        *,
        model: Any = None,
        messages: list[Any] | None = None,
        system_prompt: Any = None,
        tools: list[_ToolInput] | None = None,
        agent_tools: list[Any] | None = None,
        vended_tools: list[Any] | None = None,
        vended_plugins: list[Any] | None = None,
        mcp_clients: list[Any] | None = None,
        name: str | None = None,
        id: str | None = None,
        description: str | None = None,
        tool_executor: Any = None,
        display_output: bool | None = None,
        trace_attributes: list[Any] | None = None,
        trace_context: Any = None,
        session: Any = None,
        conversation_manager: Any = None,
        retry: Any = None,
        structured_output_schema: str | None = None,
        app_state: dict[str, Any] | None = None,
        model_state: dict[str, Any] | None = None,
    ) -> None:
        self._tools: list[Tool | PydanticTool] = [_coerce_tool(t) for t in (tools or [])]
        identity = None
        if name is not None or id is not None or description is not None:
            identity = _t.AgentIdentity(name=name, id=id, description=description)

        self._config = _t.AgentConfig(
            model=model,
            model_params=None,
            messages=messages,
            system_prompt=(_coerce_prompt(system_prompt) if system_prompt is not None else None),
            tools=[t.to_spec() for t in self._tools] or None,
            agent_tools=agent_tools,
            vended_tools=vended_tools,
            vended_plugins=vended_plugins,
            mcp_clients=mcp_clients,
            identity=identity,
            tool_executor=tool_executor,
            display_output=display_output,
            trace_attributes=trace_attributes,
            trace_context=trace_context,
            session=session,
            conversation_manager=conversation_manager,
            retry=retry,
            structured_output_schema=structured_output_schema,
            app_state=json.dumps(app_state) if app_state else None,
            model_state=json.dumps(model_state) if model_state else None,
        )
        self._runtime: Any = None

    @property
    def config(self) -> _t.AgentConfig:
        return self._config

    def _ensure_runtime(self) -> Any:
        if self._runtime is None:
            from ._runtime import _AgentRuntime

            self._runtime = _AgentRuntime(self)
        return self._runtime

    async def _ensure_runtime_async(self) -> Any:
        rt = self._ensure_runtime()
        await rt.async_init()
        return rt

    def _lookup_tool(self, name: str) -> Tool | PydanticTool:
        for t in self._tools:
            if getattr(t, "name", None) == name:
                return t
        raise KeyError(f"no tool registered under name {name!r}")

    def _build_invoke_args(
        self,
        prompt: Any,
        tools: list[_ToolInput] | None,
        tool_choice: _ToolChoiceInput,
        structured_output_schema: str | None,
    ) -> _t.InvokeArgs:
        extra_tools = [_coerce_tool(t).to_spec() for t in (tools or [])] or None
        return _t.InvokeArgs(
            input=_coerce_prompt(prompt),
            tools=extra_tools,
            tool_choice=_coerce_tool_choice(tool_choice),
            structured_output_schema=structured_output_schema,
        )

    async def stream_async(
        self,
        prompt: Any,
        *,
        tools: list[_ToolInput] | None = None,
        tool_choice: _ToolChoiceInput = None,
        structured_output_schema: str | None = None,
    ) -> AsyncIterator[_t.StreamEvent]:
        """Yield :class:`StreamEvent` arms as the agent runs."""
        runtime = await self._ensure_runtime_async()
        args = self._build_invoke_args(prompt, tools, tool_choice, structured_output_schema)
        stream = await runtime.generate(args)
        async for event in stream:
            yield event

    async def invoke_async(
        self,
        prompt: Any,
        *,
        tools: list[_ToolInput] | None = None,
        tool_choice: _ToolChoiceInput = None,
        structured_output_schema: str | None = None,
    ) -> AgentResult:
        """Run the agent to completion and return an :class:`AgentResult`."""
        accumulator = _AgentResultAccumulator()
        async for event in self.stream_async(
            prompt,
            tools=tools,
            tool_choice=tool_choice,
            structured_output_schema=structured_output_schema,
        ):
            accumulator.consume(event)
        return accumulator.finalize(self)

    def invoke(
        self,
        prompt: Any,
        *,
        tools: list[_ToolInput] | None = None,
        tool_choice: _ToolChoiceInput = None,
        structured_output_schema: str | None = None,
    ) -> AgentResult:
        """Synchronous wrapper around :meth:`invoke_async`.

        Raises :class:`RuntimeError` if called from a running event loop. Use
        :meth:`invoke_async` directly in Jupyter or async frameworks.
        """
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            pass
        else:
            raise RuntimeError(
                "Agent.invoke() cannot run inside an existing event loop. "
                "Use 'await agent.invoke_async(...)' instead."
            )
        return asyncio.run(
            self.invoke_async(
                prompt,
                tools=tools,
                tool_choice=tool_choice,
                structured_output_schema=structured_output_schema,
            )
        )

    def cancel(self) -> None:
        """Cancel the in-flight invocation. Fire-and-forget."""
        if self._runtime is not None:
            self._runtime.cancel()

    async def respond(self, interrupt_id: str, response: Any) -> None:
        runtime = await self._ensure_runtime_async()
        payload = response if isinstance(response, str) else json.dumps(response)
        await runtime.respond(_t.RespondArgs(interrupt_id=interrupt_id, response=payload))

    async def get_messages(self) -> list[_t.Message]:
        return await (await self._ensure_runtime_async()).get_messages()

    async def set_messages(self, messages: list[_t.Message]) -> None:
        await (await self._ensure_runtime_async()).set_messages(messages)

    async def get_app_state(self) -> dict[str, Any]:
        return await (await self._ensure_runtime_async()).get_app_state()

    async def set_app_state(self, state: dict[str, Any]) -> None:
        await (await self._ensure_runtime_async()).set_app_state(state)

    async def get_model_state(self) -> dict[str, Any]:
        return await (await self._ensure_runtime_async()).get_model_state()

    async def set_model_state(self, state: dict[str, Any]) -> None:
        await (await self._ensure_runtime_async()).set_model_state(state)


class _AgentResultAccumulator:
    """Folds the stream of events into the fields of an :class:`AgentResult`."""

    def __init__(self) -> None:
        self._stop: _t.StopEvent | None = None
        self._last_message: _t.Message | None = None
        self._interrupts: list[_t.Interrupt] = []

    def consume(self, event: _t.StreamEvent) -> None:
        if isinstance(event, _t.StreamEvent_MessageAdded):
            self._last_message = event.value.message
        elif isinstance(event, _t.StreamEvent_ModelMessage):
            self._last_message = event.value.message
        elif isinstance(event, _t.StreamEvent_Stop):
            self._stop = event.value
        elif isinstance(event, _t.StreamEvent_AgentResult):
            self._stop = event.value.stop
        elif isinstance(event, _t.StreamEvent_Interrupt):
            self._interrupts.append(event.value)

    def finalize(self, agent: Agent) -> AgentResult:
        stop = self._stop
        last = self._last_message
        if last is None:
            last = _t.Message(role=_t.Role.ASSISTANT, content=[], metadata=None)
        return AgentResult(
            stop_reason=stop.reason if stop is not None else _t.StopReason.END_TURN,
            last_message=last,
            usage=stop.usage if stop is not None else None,
            metrics=None,
            structured_output=(json.loads(stop.structured_output) if stop and stop.structured_output else None),
            interrupts=self._interrupts or None,
        )


_HookEventT = TypeVar("_HookEventT")
_HookCallback = Callable[[Any], Any]


@runtime_checkable
class HookProvider(Protocol):
    """Bundle of related hook registrations."""

    def register_hooks(self, registry: HookRegistry) -> None: ...


class HookRegistry:
    """Register callbacks keyed by ``StreamEvent`` arm class.

    Each arm of the wire ``stream-event`` variant is a distinct Python class
    (``StreamEvent_TextDelta``, ``StreamEvent_Stop``, ...). Subscribers match
    by exact class.

    Callbacks for arms whose name begins with ``After`` dispatch in reverse
    registration order, mirroring teardown semantics. Everything else
    dispatches FIFO.
    """

    def __init__(self) -> None:
        self._callbacks: dict[type, list[_HookCallback]] = {}

    def add_callback(
        self,
        event_type: type[_HookEventT],
        callback: Callable[[_HookEventT], Any],
    ) -> Callable[[], None]:
        entries = self._callbacks.setdefault(event_type, [])
        entry = typing.cast(_HookCallback, callback)
        entries.append(entry)

        def _remove() -> None:
            try:
                self._callbacks[event_type].remove(entry)
            except (KeyError, ValueError):
                pass

        return _remove

    def add_hook(self, provider: HookProvider) -> None:
        provider.register_hooks(self)

    def dispatch(self, event: Any) -> None:
        callbacks = self._callbacks_for(event)
        if any(inspect.iscoroutinefunction(cb) for cb in callbacks):
            raise RuntimeError(f"event={type(event).__name__} | use dispatch_async for async callbacks")
        for cb in callbacks:
            cb(event)

    async def dispatch_async(self, event: Any) -> None:
        for cb in self._callbacks_for(event):
            result = cb(event)
            if inspect.iscoroutine(result):
                await typing.cast(Awaitable[Any], result)

    def _callbacks_for(self, event: Any) -> list[_HookCallback]:
        entries = self._callbacks.get(type(event), [])
        return list(reversed(entries)) if type(event).__name__.startswith("After") else list(entries)


class AgentResult:
    """Terminal result of an agent invocation."""

    def __init__(
        self,
        *,
        stop_reason: _t.StopReason,
        last_message: _t.Message,
        invocation_state: dict[str, Any] | None = None,
        traces: list[_t.AgentTrace] | None = None,
        metrics: _t.AgentMetrics | None = None,
        usage: _t.Usage | None = None,
        structured_output: Any = None,
        interrupts: list[_t.Interrupt] | None = None,
    ) -> None:
        self.stop_reason = stop_reason
        self.last_message = last_message
        self.invocation_state = invocation_state if invocation_state is not None else {}
        self.traces = traces
        self.metrics = metrics
        self.usage = usage
        self.structured_output = structured_output
        self.interrupts = interrupts

    @property
    def context_size(self) -> int | None:
        return self.metrics.latest_context_size if self.metrics else None

    @property
    def projected_context_size(self) -> int | None:
        return self.metrics.projected_context_size if self.metrics else None

    def __str__(self) -> str:
        """Concatenate text from TextBlock and ReasoningBlock content."""
        chunks: list[str] = []
        for block in self.last_message.content:
            tag = getattr(block, "tag", None)
            payload = getattr(block, "payload", None)
            if tag == "text" and payload is not None:
                chunks.append(payload.text)
            elif tag == "reasoning" and payload is not None and payload.text:
                chunks.append(payload.text)
        return "\n".join(chunks)
